FROM mrrrgn/{{ mock_target }}
MAINTAINER  Morgan Reece Phillips winter2718@gmail.com
{% if mock_packages %}
RUN yum update -y
RUN yum install -y \{% for pkg in mock_packages %}
    {{ pkg }}{% if pkg != mock_packages[-1] %}\{% endif %}{% endfor %}{% endif %}
