FROM mrrrgn/mozilla-centos6-x86_64
MAINTAINER  Morgan Reece Phillips winter2718@gmail.com

RUN yum update -y
RUN yum install -y \
    autoconf213\
    python\
    mozilla-python27\
    zip\
    mozilla-python27-mercurial\
    git\
    ccache\
    perl-Test-Simple\
    perl-Config-General\
    yasm\
    wget\
    mpfr\
    xorg-x11-font*\
    imake\
    gcc45_0moz3\
    gcc454_0moz1\
    gcc472_0moz1\
    gcc473_0moz1\
    yasm\
    ccache\
    valgrind\
    dbus-x11\
    glibc-static\
    libstdc++-static\
    gtk2-devel\
    libnotify-devel\
    alsa-lib-devel\
    libcurl-devel\
    wireless-tools-devel\
    libX11-devel\
    libXt-devel\
    mesa-libGL-devel\
    gnome-vfs2-devel\
    GConf2-devel\
    gcc45_0moz3\
    gcc454_0moz1\
    gcc472_0moz1\
    gcc473_0moz1\
    yasm\
    ccache\
    pulseaudio-libs-devel\
    gstreamer-devel\
    gstreamer-plugins-base-devel\
    freetype-2.3.11-6.el6_1.8.x86_64\
    freetype-devel-2.3.11-6.el6_1.8.x86_64
